services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      PULSAR_ADDRESS: pulsar://pulsar:6650
      PULSAR_TOPIC: identity-provider-topic
      PULSAR_PRODUCER_NAME: identity-provider-producer
    ports:
      - 8080:8080
    volumes:
      - ./target/keycloak-pulsar-event-listener.jar:/opt/keycloak/providers/keycloak-pulsar-event-listener.jar:z
    depends_on:
      - pulsar
  pulsar:
    container_name: pulsar
    image: apachepulsar/pulsar:latest
    ports:
      - 8081:8080
      - 6650:6650
    environment:
      PULSAR_MEM: " -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: bin/pulsar standalone